# Generated by Django 3.2.11 on 2022-09-07 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetImporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_params', models.JSONField(blank=True, null=True)),
                ('last_imported', models.DateTimeField(blank=True, null=True)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='importer', to='adminManager.adminsource')),
            ],
        ),
    ]
