# Generated by Django 3.2.11 on 2022-11-12 23:54

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adminImporter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetimporter',
            name='import_params_new',
            field=django_jsonform.models.fields.JSONField(blank=True, null=True),
        ),
    ]
