# Generated by Django 3.2.11 on 2022-11-13 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminImporter', '0003_rename_import_params_datasetimporter_import_params_old'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasetimporter',
            old_name='import_params_new',
            new_name='import_params',
        ),
    ]
