# Generated by Django 3.2.11 on 2022-12-11 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminManager', '0004_remove_adminname_adminmanage_name_4a5d6b_idx'),
        ('adminImporter', '0004_rename_import_params_new_datasetimporter_import_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetimporter',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importers', to='adminManager.adminsource'),
        ),
    ]
