# Generated by Django 3.2.16 on 2023-04-14 19:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adminImporter', '0005_alter_datasetimporter_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasetimporter',
            old_name='last_imported',
            new_name='status_updated',
        ),
        migrations.AddField(
            model_name='datasetimporter',
            name='import_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Importing', 'Importing'), ('Imported', 'Imported'), ('Failed', 'Failed')], default=datetime.datetime(2023, 4, 14, 19, 31, 57, 672959, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
