# Generated by Django 3.2.16 on 2023-04-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminImporter', '0006_auto_20230414_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetimporter',
            name='import_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Importing', 'Importing'), ('Imported', 'Imported'), ('Failed', 'Failed')], default='Pending', max_length=100),
        ),
    ]
