# Generated by Django 3.2.16 on 2023-04-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminImporter', '0008_alter_datasetimporter_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetimporter',
            name='import_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
