# Generated by Django 3.2.11 on 2022-10-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminManager', '0002_auto_20220926_0836'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='admin',
            index=models.Index(fields=['minx', 'miny', 'maxx', 'maxy'], name='adminManage_minx_def736_idx'),
        ),
    ]
