# Generated by Django 3.2.11 on 2022-12-11 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminManager', '0003_admin_adminmanage_minx_def736_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='adminname',
            name='adminManage_name_4a5d6b_idx',
        ),
    ]
