# Generated by Django 3.2.16 on 2023-04-15 11:53

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('adminManager', '0004_remove_adminname_adminmanage_name_4a5d6b_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adminname',
            index=models.Index(django.db.models.functions.text.Upper('name'), name='admin_name_upper_idx'),
        ),
    ]
