# Generated by Django 3.2.16 on 2023-04-15 17:30

import adminManager.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminManager', '0005_adminname_admin_name_upper_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='geom',
            field=adminManager.fields.GeometryField(blank=True, null=True),
        ),
    ]
