# Generated by Django 3.2.16 on 2023-04-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminManager', '0007_auto_20230419_1328'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='admin',
            name='adminManage_minx_def736_idx',
        ),
        migrations.AddIndex(
            model_name='admin',
            index=models.Index(fields=['parent'], name='adminManage_parent__b4defd_idx'),
        ),
        migrations.AddIndex(
            model_name='admin',
            index=models.Index(fields=['source'], name='adminManage_source__fa56e0_idx'),
        ),
        migrations.AddIndex(
            model_name='admin',
            index=models.Index(fields=['minx'], name='adminManage_minx_3c6388_idx'),
        ),
        migrations.AddIndex(
            model_name='admin',
            index=models.Index(fields=['miny'], name='adminManage_miny_47d6b2_idx'),
        ),
        migrations.AddIndex(
            model_name='admin',
            index=models.Index(fields=['maxx'], name='adminManage_maxx_00bb3d_idx'),
        ),
        migrations.AddIndex(
            model_name='admin',
            index=models.Index(fields=['maxy'], name='adminManage_maxy_7ab730_idx'),
        ),
    ]
