# Generated by Django 3.2.16 on 2023-04-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminManager', '0008_auto_20230425_2347'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='admin',
            index=models.Index(fields=['source', 'minx', 'maxx', 'miny', 'maxy'], name='adminManage_source__42c296_idx'),
        ),
    ]
