# Generated by Django 3.2.16 on 2023-05-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminManager', '0009_admin_adminmanage_source__42c296_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='adminname',
            name='admin_name_upper_idx',
        ),
        migrations.AlterField(
            model_name='adminname',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
