# Generated by Django 3.2.16 on 2023-05-02 17:58

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('adminManager', '0010_auto_20230502_1958'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adminname',
            index=models.Index(django.db.models.functions.text.Upper('name'), name='admin_name_upper_idx'),
        ),
    ]
