# Generated by Django 3.2.16 on 2023-05-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminManager', '0011_adminname_admin_name_upper_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='admin',
            index=models.Index(fields=['minx', 'maxx', 'miny', 'maxy'], name='adminManage_minx_54f4ab_idx'),
        ),
    ]
